"""
AXIS TaskRunner — interprets natural-language task strings and dispatches
them to registered handler coroutines.

Pattern matching is intentionally simple: each handler declares a list of
trigger keywords and a regex to extract arguments.  Add new handlers by
appending to _HANDLERS in this module.
"""

import re
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Awaitable

from utils.logger import get_logger

log = get_logger("axis.task_runner")


class TaskResult:
    def __init__(self, success: bool, message: str, artifacts: dict = None):
        self.success   = success
        self.message   = message
        self.artifacts = artifacts or {}
        self.timestamp = datetime.now(timezone.utc).isoformat()

    def __str__(self):
        status = "OK" if self.success else "FAIL"
        return f"[{status}] {self.message}"


class TaskRunner:
    def __init__(self, graph, logger=None):
        self._graph = graph
        self._log   = logger or log

    async def run(self, description: str) -> TaskResult:
        desc = description.strip()
        self._log.info(f"Running task: {desc!r}")

        for handler_fn, keywords in _HANDLERS:
            if any(kw in desc.lower() for kw in keywords):
                try:
                    result = await handler_fn(desc, self._graph, self._log)
                    self._log.info(str(result))
                    return result
                except Exception as exc:
                    msg = f"Handler failed: {exc}"
                    self._log.error(msg)
                    return TaskResult(False, msg)

        return await _handle_fallback(desc, self._graph, self._log)


# ---------------------------------------------------------------------------
# Handlers
# ---------------------------------------------------------------------------

async def _handle_news_brief(desc: str, graph, log) -> TaskResult:
    from tasks.news    import fetch_ai_news
    from tasks.file_io import save_markdown

    # Extract story count
    count = 3
    m = re.search(r"top\s+(\d+)", desc, re.I)
    if m:
        count = int(m.group(1))

    # Extract output path
    output_path = "~/AXIS/daily_brief.md"
    m = re.search(r"([\w~/.-]+\.md)", desc)
    if m:
        output_path = m.group(1)
        if not output_path.startswith(("/", "~")):
            output_path = f"~/AXIS/{output_path}"

    log.info(f"Fetching top {count} AI news stories…")
    t0 = time.time()
    stories = fetch_ai_news(count=count)
    elapsed = time.time() - t0
    log.info(f"Fetched {len(stories)} stories in {elapsed:.1f}s")

    if not stories:
        return TaskResult(False, "No stories returned — check network")

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# AXIS Daily Brief",
        f"",
        f"**Generated:** {now}  ",
        f"**Query:** Top {count} AI news stories",
        f"",
        f"---",
        f"",
    ]
    for i, s in enumerate(stories, 1):
        lines.append(f"## {i}. {s['title']}")
        lines.append(f"")
        if s.get("description"):
            lines.append(f"{s['description']}")
            lines.append(f"")
        lines.append(f"**Source:** {s.get('source', 'N/A')}  ")
        lines.append(f"**Published:** {s.get('pub_date', 'N/A')}  ")
        if s.get("link"):
            lines.append(f"**Link:** [{s['link']}]({s['link']})")
        lines.append(f"")
        lines.append(f"---")
        lines.append(f"")

    lines.append(f"*Generated by AXIS Memory Graph System*")
    content = "\n".join(lines)

    saved = save_markdown(content, output_path)

    # Persist to memory graph
    brief_node = graph.add_node(
        content=f"Daily brief generated: {now} — {len(stories)} stories",
        node_type="event",
        tags=["news", "daily_brief", "ai"],
        metadata={"output_path": saved, "story_count": len(stories)},
        pinned=False,
    )
    for s in stories:
        story_node = graph.add_node(
            content=f"AI News: {s['title']}",
            node_type="fact",
            tags=["news", "ai"],
            metadata={"link": s.get("link"), "source": s.get("source"), "pub_date": s.get("pub_date")},
        )
        graph.link(brief_node.id, story_node.id, "contains", weight=1.0)

    return TaskResult(
        success   = True,
        message   = f"Saved {len(stories)} stories → {saved}",
        artifacts = {"path": saved, "story_count": len(stories), "stories": stories},
    )


async def _handle_fallback(desc: str, graph, log) -> TaskResult:
    log.info(f"No specific handler matched — acknowledging task: {desc!r}")
    return TaskResult(
        success=True,
        message=f"Task received: {desc}",
        artifacts={},
    )


# Registry: (handler_coroutine, trigger_keywords)
_HANDLERS: list[tuple[Callable[..., Awaitable[TaskResult]], list[str]]] = [
    (_handle_news_brief, ["ai news", "news stories", "artificial intelligence news", "news today"]),
]
